### PR TITLE
Add selection option

### PR DESCRIPTION
**Pull request by clemera**
Hi,

Thanks for your great extension, it is the best I could find for taking screenshots in firefox! I was missing the option to select the area I want to screenshot, so this PR adds this option. Let me know if anything is missing.

### CODE REVIEW

**Comment by M-Reimer** [comment]
Initially I didn't have a plan to do this as the goal was to create a simple screenshot tool for getting an image for editing externally. But your change looks pretty nice. I'll have a closer look into your changes ASAP.

**Comment by clemera** [comment]
Thanks, I really like that it is simple and does not try to do to much. The selection option speeds things up if you don't plan any external editing but only need portions of a page.

**Comment by CarltonTheDoorman** [comment]
5 / 5
Just wonderful add-on.
To have money I would ask to add it for Chrome (Edge).
But don't have money sorry.

Thanks for this extension. I use more Chrome sorry.

**Comment by M-Reimer** [comment]
Merged, but I've edited out your "SendMessage" callback to see what is going wrong here.

To resolve the underlying issue I made the "Select" function return a Promise and add a callback for it in the "OnMessage" callback.

**Comment by M-Reimer** [comment]
> 5 / 5
> Just wonderful add-on.
> To have money I would ask to add it for Chrome (Edge).
> But don't have money sorry.
> 
> Thanks for this extension. I use more Chrome sorry.

Off topic here so I won't discuss this in detail. Just one thing: Don't use Chrome :stuck_out_tongue:

**Comment by clemera** [comment]
Ah nice, thanks! I'm still wrapping my head around JS and async programming sorry for that.

**Pull request closed without merging**
