### PR TITLE
Fixes & Improvements & Initital Legacy Support (v57+)

### PR DESCRIPTION
**Pull request by jakwings**
Fixes:
- <del>Handle cases when window.devicePixelRatio =/= 1</del>
- Handle pages with Right-To-Left scrolling

Improvements:
- Crop scrollbar area
- Better debug messages
- Allow copying jpeg data to clipboard
- Reset position of sticky elements for full page capture
- Support page size larger than built-in screenshot tool does

```
 LICENSE-UPNG.js          |    24 +
 LICENSE-inkjet.js        |    24 +
 LICENSE-pako.js          |    24 +
 Makefile                 |     5 +
 _globals.js              |    46 +-
 background.js            |   479 +-
 contentscript.js         |   353 +-
 default-preferences.json |     6 +-
 imagecomments.js         |    16 +-
 lib/inkjet.js            | 24195 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 lib/pako.js              |  3978 +++++++++++
 lib/upng.js              |  1107 +++
 lib/worker-jpeg.js       |     9 +
 lib/worker-png.js        |     8 +
 manifest.json            |     7 +-
 15 files changed, 30090 insertions(+), 191 deletions(-)
```

:tongue: ***JUST FYI IM TOO LAZY TO REBASE AND SUBMIT A REAL PATCH*** :wink:

Here is the extension file: [firefox-screenshot.zip](https://github.com/jakwings/firefox-screenshot/archive/refs/heads/master.zip)

### CODE REVIEW

**Comment by iology** [comment]
Test file updated with the latest fix!

**Comment by M-Reimer** [comment]
Thank you for all your work. Actually I'm always happy to see if someone shares improvements and new features.

But... This one makes it currently difficult to decide.

You should, at all cost, prevent to do many changes in one big commit. This makes it really difficult to follow your progress and changes. It also makes it difficult to back one or two out if they don't fit into the project goal or vision.

Currently, to be honest, I have a big tendency to just close this PR. I'm in the middle of writing a master thesis and only do coding for diversion. But let's at least try to talk about some points:

> Initital Legacy Support (v57+)
Definitively NO. Someone will have to maintain this code in future and this won't be me. This Add-on is based around an API which is able to take screenshots bigger than the current viewport. It always did. In fact there was a "take full page screenshot API" in the past that I used before migrating to the new one (which only works for Firefox 82 and up). But this old API had to run in the content script and not in the background script which was the reason why I decided to make a cut here to not bloat the codebase.

If you have a look at the support dates https://en.wikipedia.org/wiki/Firefox#Platform_availability then you'll see that the oldest version, that is still relevant, actually is 91.5.

> - Handle cases when window.devicePixelRatio =/= 1
Could actually be a good point. But I don't know what it is, where your fix is exactly and where this issue happens

> - Crop scrollbar area
Really good point. I remember that I always have a small unused space in pictures. But, again, difficult to find this one to, probably, cherry-pick this one.

> - Allow copying jpeg data to clipboard
Most probably not needed. Maybe you prove me wrong but my understanding of "copy image to clipboard" is that the intermediate PNG is just needed for the API. What actually ends on the clipboard are just the pixels. And if you use JPEG as an intermediate format, then your pixels will be all blurry from compression artifacts.

> - Reset position of sticky elements for full page capture
Could be a good point but again: I don't see where this is fixed and where this is an issue.

> - Support page size larger than built-in screenshot tool does
Requested many times and I still think people, needing this, should better use a PDF export Add-on. It's just bad to archive big websites as images. For example this makes it impossible to do full page search on them.

But even this should be possible without complex scrolling. For most big pages you probably only need two or three "larger size" screenshots to then "glue them together.


Probably it wouldn't be the worst idea to cover individual fixes and features step by step without replacing the whole codebase. Actually I've just activated discussions here, so feel free to use it: https://github.com/M-Reimer/savescreenshot/discussions

**Comment by iology** [comment]
> Currently, to be honest, I have a big tendency to just close this PR.

No problem. Just to let you know what I have done and you can see a git diff quickly on github. But I hope you keep this open so others can find this fork more easily. ;-)

Haha, a big block of code about `use_js_scroll` and `use_css_scroll` are hacks and experiments before I found the deprecated `drawWindow()` API. Actually these two routines are blocked by `use_native = true` (either captureTab or drawWindow).

> And if you use JPEG as an intermediate format, then your pixels will be all blurry from compression artifacts.

The option is there so I think the new behavior is less misleading. Blurry effect is fun sometimes.

> Someone will have to maintain this code (for legacy browsers) in future

No, the `drawWindow` api is never used in new browsers, no worry, can just point people to an old version or my fork of this extension.

> It's just bad to archive big websites as images.

It depends. PDF is harder to edit. I like web comics and don't want to deal with PDF layout, HTML+JS/CSS, I need to close my browser so I do a quick backup (after applying my custom css stylesheet) and no need to go online, download and set up the layout again. Anyway if I need screenshots and this tool does the job, then it's okay, not much to think about here.

>I don't see where this is fixed and where this (sticky elements) is an issue.

Sticky elements, like the sticky header on GitHub readme file, the sticky header on this pull request page. Anyway there is time they are annoying as hell.

> difficult to decide

So I see you most want these?
* Handle cases when window.devicePixelRatio =/= 1 (MacBook, Retina Display, new hardware...)
* Crop scrollbar area (key point: scrollbar width = `window.innerWidth - document.documentElement.clientWidth`, its not included in `document.documentElement.scrollWidth`)

**Comment by iology** [comment]
> where your fix is exactly and where this issue happens

Oh yes, window.devicePixelRatio is not an issue before I extended the capture area (the image blob was just passed around as opague object). :-P

**Comment by iology** [comment]
> Handle pages with Right-To-Left scrolling

`browser.tabs.captureTab` accept negative `rect.x` and `rect.y` when "direction: rtl" is in effect.

> But even this should be possible without complex scrolling. For most big pages you probably only need two or three "larger size" screenshots to then "glue them together.

"most big pages" is really "big" and "simple" --> simply tough jobs :(

**Comment by iology** [comment]
> Handle pages with Right-To-Left scrolling

`browser.tabs.captureTab` accepts negative `rect.x` and `rect.y` when "direction: rtl" is in effect.

> But even this should be possible without complex scrolling. For most big pages you probably only need two or three "larger size" screenshots to then "glue them together.

"most big pages" is really "big" and "simple" --> simply tough jobs :(

**Comment by M-Reimer** [comment]
> No problem. Just to let you know what I have done and you can see a git diff quickly on github. But I hope you keep this open so others can find this fork more easily. ;-)

The goal of a Pull Request actually is to either have it merged or get it closed at some point.

You have some really interesting ideas, but in the current state it is unfortunately impossible for me to merge this Pull Request. Especially as you keep adding stuff that can not make it into my code. For example some global utilities are in a git submodule for a reason. I just recently moved it to there to reduce code duplication. I won't move it back.

It would really help me if you could create smaller Pull Requests with one feature at a time. Preferrably with short discussion before so I don't have to close a Pull Request without merging it.

- Please no Scrolling. There are literally dozens of Add-ons on AMO that do scrolling as this is the only way to be compatible with Google Chrome (which does not allow screenshots beyond viewport
- Please no legacy stuff. Everything that is no longer maintained by Mozilla is dangerous and should not be used nor supported by Add-on developers.

**Comment by M-Reimer** [comment]
Addition: Probably I could manually pick some of the changes from your code directly, so I'll keep that in mind and add a note with your name to every commit that resulted from that.

But pre-made Pull Requests that actually merge without conflicts would make work so much easier (for me) as I'm a bit busy these days.

**Comment by iology** [comment]
> Preferrably with short discussion before so I don't have to close a Pull Request without merging it.

I don't mind.  We can read each other's code and discuss anytime.

> I won't move it back.

> Please no...

I will refactor everything, I'm such a guy. ;) Thanks for open sourcing!

**Comment by M-Reimer** [comment]
Would you mind creating smaller Pull Requests for individual stuff. I mean "non invasive" or "less invasive" Pull Requests :stuck_out_tongue: 

I tried to reproduce the "RTL" issue. My test page was simply https://ar.wikipedia.org/wiki/
And I am able to do selections with my current code just fine. No issues there

Do you think you could create a simple Pull Request that fixes the scrollbar space issue in an "as simple as possible" manner?

> I will refactor everything, I'm such a guy. ;) Thanks for open sourcing!

Will just not help much if your intention was to get changes back into the original project.

**Pull request closed without merging**
