### PR TITLE
Features + localization

### PR DESCRIPTION
**Pull request by mshot**
+ FEATURE: Editable shortcut (default Ctrl+Shift+L)
+ FEATURE: Editable file name format/prefix (default %y%m%d_%H%M%S_%h)
           DateTime, host name, URL, MD5 from URL, page title
           Example: %y%m%d_%H%M%S_%h -> 20181224_123805_www.abc.de
+ OPTIONS entry for shortcut & format/prefix
+ FEATURE: Exposing SaveScreenshot with exportFunction to enable calls from developer console
+ LOCALIZATION: czech localization, english ones added to other languages for new labels

### CODE REVIEW

**Comment by mshot** [comment]
It's fine, as i allready have signed xpi for my needs with those features so take your time & good luck with your exams :)

**Comment by M-Reimer** [comment]
Some first thoughts:
- Why the MD5 sum generation? Do you actually have any "real" use case for this? This is pretty much code just to have something "not human readable"
- The exported function most probably is also visible from website javascript. I'll try that. If this is the case, I can't add this.
- The prefix format description also needs localization

**Comment by mshot** [comment]
whole %Variable part is inspired by plugin we used earlier (PearlCrescent), we do not use MD5 afaik, possible usage i can imagine is to have (with timetags) unique file names at same page (testing scenario)

exported function is visible, thats whole point of it - we use it in Selenium3+Gecko driven Firefox to get fullpage screenshots (due to changes between Selenium2 to Selenium3 we are no longer able to use shortcuts to take fullpage screenshots with plugins) - this leads to something like: `((IJavaScriptExecutor)webDriver).ExecuteScript("SaveScreenshot(0, 0, window.innerWidth + window.scrollMaxX, window.innerHeight + window.scrollMaxY,\"PNG\");");`
-i'm not saying u have to integrate it only that it has legitimate purpose :)

sorry about that last part - i forgot to localizate it -> sounds like TODO for me

**Comment by M-Reimer** [comment]
> possible usage i can imagine is to have (with timetags) unique file names at same page (testing scenario)

I think in this case a real timestamp would be better as it's shorter and human readable. I'd prefer to keep the whole MD5 code out for at least until someone requests it with a good reason.

> exported function is visible, thats whole point of it

It also **is** visible to the page javascript. I don't think that this is a serious security problem, but it may at least be pretty annoying if some website starts to abuse this. In theory, this allows to save screenshots in an endless loop.

Adding this has the potential of getting my Addon banned from addons.mozilla.org, so I'll not add this. If there was some way to just export this to the development tools, this would be OK.

**Comment by mshot** [comment]
y, i agree that MD5 is not really usefull compared to rest of variables

to exported function - is possible to bind it to variable(default off) or not? (i usually don't play with .js :) ) - we use it with custom profiles at forward known domains not in the wild browsing so we don't need it always turned on

**Comment by M-Reimer** [comment]
https://github.com/M-Reimer/savescreenshot/commit/71d483e775f0a7465e47f2fb4295cc5694602231
https://github.com/M-Reimer/savescreenshot/commit/505d68cff28c3402b0b691b287fe6aa6b182c3bc

I don't know if you still use "Save Screenshot" but if you still need some way to control it from externally, I could ask in the Addons developer mailing list if there is some save way to do this.

**Pull request closed without merging**
